#!/usr/bin/env bash
# Publish a Clash YAML subscription over HTTPS using nginx + an existing
# Let's Encrypt cert. The YAML carries one Hysteria2 node (with port hopping)
# and one VLESS Reality node, plus PROXY / AUTO groups.
#
# Subscription URL is path-token gated: only /<32-hex>.yaml resolves.
# The token persists in /etc/sing-box/sub_token across reruns so the URL
# you hand to clients does not silently rotate.
set -euo pipefail

DOMAIN=""
SUB_DIR=/var/www/sub
TOKEN_FILE=/etc/sing-box/sub_token

SERVER_IP=""
VLESS_UUID=""
VLESS_PORT=18443
REALITY_PUBKEY=""
REALITY_SHORTID=""
HANDSHAKE_SERVER="www.microsoft.com"
HY2_PORT=36712
HY2_PASSWORD=""
HY2_PORTS="20000-50000"

usage() {
  cat <<HLP
Usage: sudo $0 \\
  --domain <vpn.example.com> \\
  --server-ip <1.2.3.4> \\
  --vless-uuid <uuid> \\
  --reality-pubkey <pubkey> \\
  --reality-shortid <hex> \\
  --hy2-password <pwd> \\
  [--vless-port 18443] [--hy2-port 36712] \\
  [--hy2-ports 20000-50000] \\
  [--handshake-server www.microsoft.com]

The cert at /etc/letsencrypt/live/<domain>/{fullchain,privkey}.pem must already exist.
HLP
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain) DOMAIN="$2"; shift 2 ;;
    --server-ip) SERVER_IP="$2"; shift 2 ;;
    --vless-uuid) VLESS_UUID="$2"; shift 2 ;;
    --vless-port) VLESS_PORT="$2"; shift 2 ;;
    --reality-pubkey) REALITY_PUBKEY="$2"; shift 2 ;;
    --reality-shortid) REALITY_SHORTID="$2"; shift 2 ;;
    --handshake-server) HANDSHAKE_SERVER="$2"; shift 2 ;;
    --hy2-port) HY2_PORT="$2"; shift 2 ;;
    --hy2-ports) HY2_PORTS="$2"; shift 2 ;;
    --hy2-password) HY2_PASSWORD="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "ERROR: unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

[[ $EUID -eq 0 ]] || { echo "ERROR: run as root" >&2; exit 1; }
for v in DOMAIN SERVER_IP VLESS_UUID REALITY_PUBKEY REALITY_SHORTID HY2_PASSWORD; do
  if [[ -z "${!v}" ]]; then
    echo "ERROR: --${v,,//_/-} is required" >&2
    usage
    exit 1
  fi
done

CERT="/etc/letsencrypt/live/$DOMAIN/fullchain.pem"
KEY="/etc/letsencrypt/live/$DOMAIN/privkey.pem"
[[ -r "$CERT" ]] || { echo "ERROR: $CERT not readable; issue cert first" >&2; exit 1; }
[[ -r "$KEY"  ]] || { echo "ERROR: $KEY not readable"  >&2; exit 1; }

if [[ -s "$TOKEN_FILE" ]]; then
  TOKEN=$(cat "$TOKEN_FILE")
else
  install -d -m 700 "$(dirname "$TOKEN_FILE")"
  TOKEN=$(openssl rand -hex 16)
  echo "$TOKEN" > "$TOKEN_FILE"
  chmod 600 "$TOKEN_FILE"
fi
SUB_PATH="$SUB_DIR/${TOKEN}.yaml"

install -d -m 755 "$SUB_DIR"
cat > "$SUB_PATH" <<YAML
# generated by publish-clash-subscription.sh
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: false

dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver: [223.5.5.5, 8.8.8.8]
  nameserver:
    - https://dns.google/dns-query
    - https://1.1.1.1/dns-query
  fallback:
    - https://dns.cloudflare.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN

proxies:
  - name: "${DOMAIN}-HY2"
    type: hysteria2
    server: $DOMAIN
    port: $HY2_PORT
    ports: "$HY2_PORTS"
    password: $HY2_PASSWORD
    sni: $DOMAIN
    alpn: [h3]
    skip-cert-verify: false
    udp: true

  - name: "${DOMAIN}-Reality"
    type: vless
    server: $SERVER_IP
    port: $VLESS_PORT
    uuid: $VLESS_UUID
    network: tcp
    udp: true
    tls: true
    flow: xtls-rprx-vision
    servername: $HANDSHAKE_SERVER
    client-fingerprint: chrome
    reality-opts:
      public-key: $REALITY_PUBKEY
      short-id: $REALITY_SHORTID

proxy-groups:
  - name: "PROXY"
    type: select
    proxies: ["AUTO", "${DOMAIN}-HY2", "${DOMAIN}-Reality", DIRECT]
  - name: "AUTO"
    type: url-test
    proxies: ["${DOMAIN}-HY2", "${DOMAIN}-Reality"]
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50

rules:
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
YAML
chmod 644 "$SUB_PATH"

NGX="/etc/nginx/sites-available/clash-sub-${DOMAIN}"
cat > "$NGX" <<NGINX
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $DOMAIN;

    ssl_certificate     $CERT;
    ssl_certificate_key $KEY;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_session_cache   shared:CLASHSUB:10m;

    root $SUB_DIR;
    autoindex off;
    server_tokens off;

    location ~ "^/[a-f0-9]{32}\.yaml\$" {
        default_type text/yaml;
        add_header Cache-Control "no-store" always;
        try_files \$uri =404;
    }

    location = / { return 404; }
    location /   { return 404; }
}
NGINX
ln -sf "$NGX" "/etc/nginx/sites-enabled/clash-sub-${DOMAIN}"
nginx -t
systemctl reload nginx

URL="https://$DOMAIN/${TOKEN}.yaml"
echo
echo "Subscription URL:"
echo "  $URL"
echo
echo "Self-test:"
curl -sS -o /dev/null -w '  HTTP %{http_code}  ssl_verify_result=%{ssl_verify_result}\n' "$URL"
